### ISSUE TITLE
alice 80

### ISSUE THREAD

**Issue by tbremer** [Ginakira/dotfiles#1]
Weird question, I've been scouring github trying to find folks who have modded their Alice80 to use a newer version of VIA and I saw your dotfiles, are you using the limited via compatible firmware provided by Feker/Epomaker, or have you found a way to flash new firmware on it?

**Comment by Ginakira** [comment]
> Weird question, I've been scouring github trying to find folks who have modded their Alice80 to use a newer version of VIA and I saw your dotfiles, are you using the limited via compatible firmware provided by Feker/Epomaker, or have you found a way to flash new firmware on it?

Hi tbremer, I am using the firmware provided by Feker. It works well on basic VIA features, though some features are unavailable. But it's enough for me.

The Alice 80 firmware for VIA hasn't any update for a long time.It is provided via QQ group in China. I see the current version number is 1212, update date is 2023-04-29. My current version is also this.

**Comment by tbremer** [comment]
> > Weird question, I've been scouring github trying to find folks who have modded their Alice80 to use a newer version of VIA and I saw your dotfiles, are you using the limited via compatible firmware provided by Feker/Epomaker, or have you found a way to flash new firmware on it?
> 
> Hi tbremer, I am using the firmware provided by Feker. It works well on basic VIA features, though some features are unavailable. But it's enough for me.
> 
> The Alice 80 firmware for VIA hasn't any update for a long time.It is provided via QQ group in China. I see the current version number is 1212, update date is 2023-04-29. My current version is also this.

Interesting, thank you! The latest version I have found online is 1009, would you mind sharing where you got 1212? Also, does it support toggling layers, or is that still not allowed?

**Comment by Ginakira** [comment]
> > > Weird question, I've been scouring github trying to find folks who have modded their Alice80 to use a newer version of VIA and I saw your dotfiles, are you using the limited via compatible firmware provided by Feker/Epomaker, or have you found a way to flash new firmware on it?
> > 
> > 
> > Hi tbremer, I am using the firmware provided by Feker. It works well on basic VIA features, though some features are unavailable. But it's enough for me.
> > The Alice 80 firmware for VIA hasn't any update for a long time.It is provided via QQ group in China. I see the current version number is 1212, update date is 2023-04-29. My current version is also this.
> 
> Interesting, thank you! The latest version I have found online is 1009, would you mind sharing where you got 1212? Also, does it support toggling layers, or is that still not allowed?

No problem! The layer feature seems to be available in memory, but maybe I'm wrong because it's been so lang since the last configuration. 
I will send you the firmware version 1212 after work because it isn't on my work computer. (About 22:00 GMT+8)
Please tell me how to send the file to you, email or any other way convenient for you.  :)

**Comment by Ginakira** [comment]
@tbremer I upload all files to Google Drive. [File Link](https://drive.google.com/file/d/1qr6BjjiFiVzWLSeLnGpWzDIwKMkSV-bz/view?usp=drive_link)
The documents are written in Chinese, so you maybe need to translate them.
